name: Flutter

on:
  push:
    branches: [ master ]
    tags:
      - '1.0'

jobs:
  build-ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - name: Flutter action
      uses: subosito/flutter-action@v1.3.2
    - name: Build IOS
      run: |
        flutter build ios --release --no-codesign
        mkdir Payload
        mv build/ios/iphoneos/Runner.app Payload
        zip -r Runner.ipa Payload
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.GITHUB_RUN_NUMBER }}
        artifacts: "Runner.ipa"
        token: ${{ secrets.GITHUB_TOKEN }}

  build-apk:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - name: Flutter action
      uses: subosito/flutter-action@v1.3.2
    - name: Build APK
      run: |
        flutter build apk
        mv build/app/outputs/apk/release/app-release.apk app-release.apk
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.GITHUB_RUN_NUMBER }}
        artifacts: "app-release.apk"
        token: ${{ secrets.GITHUB_TOKEN }}